name: pystock-data-features
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - cloudpickle
  - pip:
    - mlflow
    - yfinance
    - jinja2
    - pandas_datareader
    - pydantic-settings
    - great-expectations
    - pandas-profiling